name: small_amap
description: 一款全新方式的高德地图插件，绝对轻量级。适配Android和IOS
version: 0.0.1
author: github@hahafather007
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter